polish..

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -54,12 +54,9 @@ jobs:
           path: ~/.m2/repository
           key: ${{ runner.os }}-m2
           restore-keys: ${{ runner.os }}-m2
-
-      - name: Build the application
-        run: mvn -Dspring.profiles.active=ci verify deploy
-
       - name: Deploy
         run: |
+
           export BP_MODE="development"
           if [ "$GITHUB_EVENT_NAME" = "create" ]; then 
               if [[  "${GITHUB_REF}" =~ "tags" ]]; then 
@@ -68,5 +65,6 @@ jobs:
           fi
           echo "BP_MODE=${BP_MODE}" 
           cd $GITHUB_WORKSPACE
+          mvn -Dspring.profiles.active=ci verify deploy || die "could not build and deploy the artifact to Artifactory."
           ./deploy/cf.sh
           ./deploy/deploy.sh
